# generates api.inc
cp mmagedit.h _api.inc

SYM="[a-zA-Z0-9_\*]\+"
TYPE="\(const \)\?\(int\|char\|bool_t\)\*\?"

echo "// auto-generated by apigen.sh" > api.inc

cat _api.inc | tr '\n' '\r' \
  | sed 's/.*\(\/\/ BEGIN\)/\1/' \
  | sed 's/\(\/\/ END API -*\).*/\1/' \
  | sed "s/external \(\(const \)\?$SYM\)\r\($SYM\)(/\$(\1, \3, /g" \
  | sed "s/\($TYPE\) \($SYM\)/\1/g" \
  | sed "s/\#[^\r]*//g" \
  | sed "s/;//g" \
  | tr '\r' '\n' >> api.inc